### ISSUE TITLE
TypeError: userCoins.get is not a function

### ISSUE THREAD

**Issue by xvvvyz** [Anchor-Protocol/anchor-earn#17] opened 2021-10-25 22:34 UTC
- The address I'm using does indeed have funds.
- After reverting [this change](https://github.com/Anchor-Protocol/anchor-earn/commit/209d449247a799cfed2ec831c24edf13260ff021#diff-017add6e6276b223744a644c9b42059df34f877c475f44f1d95cc05dcc2674c8L422) it works (cc @ALPAC-4).

```javascript
import Anchor from '@anchor-protocol/anchor-earn'; // v1.1.0

(async () => {
  const anchorEarn = new Anchor.AnchorEarn({
    address: '...',
    chain: Anchor.CHAINS.TERRA,
    network: Anchor.NETWORKS.COLUMBUS_5,
  });

  const { total_deposit_balance_in_ust: anchorBalance } =
    await anchorEarn.balance({ currencies: [Anchor.DENOMS.UST] });
})()
```

**Comment by crypt0grapher** [comment] 2021-11-20 20:38
Hey guys it looks like I'm facing the same issue. It'd be great if you can take a look into that

**Comment by crypt0grapher** [comment] 2021-11-21 11:01
The reason for the issue is that anchor-earn is not aligned with terra.js.
I see there's a PR waiting to fix that, it'll help: 
https://github.com/petes-fan-club/anchor-earn/commit/6ecc5599db9aa6f84b96fa6a46c31b536cf1b816
@cadejscroggins 
As a workaround, you can use that commit for the time being in your `package.json`
`"@anchor-protocol/anchor-earn": "git://github.com/petes-fan-club/anchor-earn.git#6ecc5599db9aa6f84b96fa6a46c31b536cf1b816",
`

**Comment by petes-fan-club** [comment] 2021-11-21 17:44
the only gotcha on that PR is that it assumes that the token appears on the first page of results. the new API provides a paginated response.. so ideally the fix for this issue should check for pagination and fetch more balances.
the PR itself is stalled on a node-16 install issue (node-gyp does give so much to everyone).

**Comment by crypt0grapher** [comment] 2021-11-21 17:46
Makes much sense, many thanks for the note @petes-fan-club

**Comment by petes-fan-club** [comment] 2021-11-21 17:48
if you know how to make node-gyp resolve itself, I'll fix up the PR.. I'm assuming just adding it to devDependencies will help

**Comment by crypt0grapher** [comment] 2021-11-21 17:52
I'm on the phone can't tell right now, I think `node-gyp-build` would be necessary as well to build the package.
At least installing that inside my docker container helped me ) I made almost the same fix as you before noticing your PR. 
The usual )

**Comment by petes-fan-club** [comment] 2021-11-22 14:39
PR was merged.. 
give it a shot.. I'll work on the edge case today

**Comment by crypt0grapher** [comment] 2021-11-22 16:36
Well, it's still a very nice update of yours if downloaded from github url, but it's not installable with npm/yarn since npm package registry holds the 10-day old version. 
I don't see if there's any github action configured for that, so it looks like this is something yet to be done - to assign a new version number and publish the change to npm.

**Comment by crypt0grapher** [comment] 2021-11-23 12:29
`yarn add @anchor-protocol/anchor-earn@2.0.0-alpha1` works like a charm.

**Closed as completed** 2023-08-21 01:06 UTC
